### ISSUE TITLE
IReportsClient.GetAllReports() does not return pagination token

### ISSUE THREAD

**Issue by IanKemp** [checkout/checkout-sdk-net#270] opened 2022-12-07 10:48 UTC
This makes it impossible to pass the pagination token to subsequent requests to retrieve subsequent pages of reports.

While the `ReportsResponse` from the aforementioned method returns a `next` link which itself contains a pagination token, it is of course not possible to pass a full link to the aforementioned method, only a token.

**Comment by Armando-Ibarra** [comment] 2022-12-12 16:04
@IanKemp I just review this with more details, and the issue is not on SDK, is on API side, because the response is not returning the token as part of the response, you can find it in `links`property however this is not correct at all.
But if it's urgent to you, you can get a workaround grabbing the pagination token from there for now
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/30295119/207093862-13219f74-2af8-4a36-8360-9e45b7874585.png">

**Comment by IanKemp** [comment] 2022-12-13 10:22
That is exactly what we ended up doing, but obviously it's quite sub-optimal.

**Comment by Armando-Ibarra** [comment] 2023-02-24 04:58
Pagination token is not going to be exposed so far by API team, will close this one as won't do

**Closed by Armando-Ibarra** 2023-02-24 04:58 UTC
