### ISSUE TITLE
.NET 6 & System.Text.Json support 

### ISSUE THREAD

**Issue by oferns** [checkout/checkout-sdk-net#160] opened 2022-02-09 10:55 UTC
Hi,
We have just started looking at checkout.com for our online ecommerce platform. We need .net 6 support and Non-Newtonsoft (ie System.Text.Json) serialization. I have cloned the repo and made the required changes but I have a couple of blockers.

1. How do I create a PR?
2. Where can I get FOUR and OAuth credentials to allow me to run the tests? (I have a sandbox account under my work email but there is no option for OAuth etc. I have a CHECKOUT_PUBLIC_KEY and a CHECKOUT_SECRET_KEY but I need a CHECKOUT_FOUR_PUBLIC_KEY, a CHECKOUT_FOUR_SECRET_KEY, a CHECKOUT_FOUR_OAUTH_CLIENT_ID, and a CHECKOUT_FOUR_OAUTH_CLIENT_SECRET to make the tests run.

Thanks,
Ollie

**Comment by rsaestrela** [comment] 2022-02-10 10:56
Hi @oferns. Thanks for creating this issue and apologies for not getting back to you sooner. This .NET project aims to offer a solution that must be compatible with most (if not all) it's consumers. We are targeting `net5.0;netstandard2.0;netcoreapp3.1` on purpose to make it compatible with most of it's integrations, from .NET 4.6.1 to the most recent version (6.0.1).

We believe it's compatible with .NET 6, but we might be missing some details. Can you please explain in detail which parts (code, dependencies, configuration) is not compatible with your platform? Why do you need a non-Newtonsoft serialization solution?

Having in consideration this is a general purpose SDK solution, understanding the right context will allow us to decide better the right move. And you're welcome to give your contribution :) PR's must be created through a fork from main. In order to run the integration tests, all these credentials are needed. Please contact the customer support for these, otherwise we can give you a hand testing your code with our / environment testing credentials. Please never commit your credentials in the code. GitHub supports environment variables, so setting all these in your fork project should be enough too make it available to run the integration tests remotely. For more information can be found [here](https://docs.github.com/en/actions/security-guides/encrypted-secrets).

Again, thanks for your contribution. We're in touch!

**Comment by oferns** [comment] 2022-02-11 09:09
Hi,
Thanks for getting back to me and apologies for my schoolboy error with the
test credentials...very poor form! I have handed out some grief to other
devs about that in the past so I shall hanging my head in shame for a
little while over that SNAFU!

As I understand it, you don't really want to be targeting netcoreapp in a
class library. You should only use netcoreapp for the application part (ie
console, aspnet, tests). Targeting .netstandard2.0 is enough here to make
the libraries compatible with .NET 4.6.2 all the way through to .NET 6

https://docs.microsoft.com/en-us/dotnet/standard/net-standard?tabs=net-standard-2-0

However, there are a few scenarios where you will want to specifically be
targeting .NET 5 & .NET 6, mostly around these libraries and their versions.

Microsoft.Extensions.Configuration.Abstractions
Microsoft.Extensions.Configuration.Binder
Microsoft.Extensions.DependencyInjection

Currently you are targeting v 3.1.22 of these libraries, and this will not
work (for example) with Azure functions v4 upwards, which require v6.0.0 +
of these libraries and support .NET 5 & 6. Conversely, Azure functions v3
and below only support .NET core, not .net 5 & 6, and only work with
v3.1.22 down. So by targeting .netstandard and using v3.1.22 in that
version, and targeting .net 5 & 6 specifically and using the v6 libraries,
you can support all of these scenarios.

So by making these changes we actually increase support across the .NET
ecosystem.

With regard to Newtonsoft.Json & System.Text.Json, System.Text.Json is only
available in .net 5 upward as part of the framework and the
maintainer/author of Newtonsoft.Json, James Newton-King, is now employed by
Microsoft and it would appear (although I cannot find any definitive
evidence) that System.Text.Json should be considered as a superior
replacement for the Newtonsoft library moving forward (
https://twitter.com/MoGutman/status/1292144339842469889) so it would seem
to be inevitable that you would need to make these changes at some point in
the future.

I received some test credentials from Manos Kapetanakis <
***@***.***> for FOUR and OAuth so that I could run
the test suite as I have made a few of the changes "blind" but
unfortunately they do not seem to work. He emailed them to me, so I can
email them directly to you but I dont want to attach them to this email. My
work email is ***@***.***

With regard to the PR, I have invalidated the keys I committed and pushed
code to remove them from the repo. I would really like to see all the
integration tests passing before I submit another PR. I also totally
understand if you are not at all interested in my PR :) but we would rather
use the officially supported package from yourselves than maintain our own.

Happy to continue the conversation and again, thank you for your time

Regards,
Ollie

**Comment by oferns** [comment] 2022-02-11 15:23
Hi,
That's really good news. I've recreated the PR after hacking the git
history to remove the creds. It should be in a position to run the
integration tests. the unit tests all still appear to be passing so I am
quietly optimistic on the integration tests passing. That said, if there
are any failures I am happy to fix them

Thanks,
Ollie

**Comment by rsaestrela** [comment] 2022-02-16 11:43
PR #165 was merged and [build ](https://github.com/checkout/checkout-sdk-net/actions/runs/1852514453) succeeded. This change will be released tomorrow. So, part of the problem is solved! Thanks for your contribution!

**Comment by Armando-Ibarra** [comment] 2023-01-09 13:54
Hi @oferns 
I review all the trace about this issue, seems that part of the issue was covered.
I'm going to close this request, but feel free to open if you need anything else.

Thanks!

**Closed by Armando-Ibarra** 2023-01-09 13:54 UTC
Labels: enhancement
